name: Jim J
favicon: null
layout_spectrum: 0.03418
typography_spectrum: 0.06195
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#83a0dc'
    - '#282c35'
    - '#b3cdfe'
    - '#070711'
    - '#445060'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
