name: Jim J
favicon: null
layout_spectrum: 0.93691
typography_spectrum: 0.06195
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#40413b'
    - '#848580'
    - '#221912'
    - '#8c5b4c'
    - '#612f14'
  brandStrength: 0.75
  lightness: 0.06712988344952464
  saturation: 0.7553236752282828
  rhythmicContrast: 0.7994175197090954
purpose: []
