name: Jim J
favicon: null
layout_spectrum: 0.80119
typography_spectrum: 0.06195
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#40413b'
    - '#848580'
    - '#221912'
    - '#8c5b4c'
    - '#612f14'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
